language: java
jdk:
  - openjdk8
secure: "LwrMDfNeEHJVPmeyoVkZvTvr4j8lunl6AihmSwgtiEAmA1+XI+CUubvmRmepeI+ya/QnN9bNk46huesg1fkPQiABHsNzTOVTns8U8fqHjrs4v1DbJ6hAN8C3dCx/53WKM0rcOveqVMoSe4eyoig3B7Iv3DNRE7X2VjFg1p9uPvEpj/iF/Gmj1VzUUe4KlAkAI70cK1yJqksarWMMf4EJmlCKAd9K2mhPTJHCf13dK6i5UjVHP1p31SdNe48AkqNm5CSub/IKf1l1R4xGHmwdzuq1zJemkGJk9Rb+cVd4zhh+q+3J/o7QCGC0LeUpv6qCCFkhmbdarxFtDsnFfPXqSKIXGvWllTJlfjlK8lzsnYQp3o4t13jIPyFrXPdHreBIGN9fSS2+TsNSGox8v1Dofayzbim62JQ/oPN20lLC3BnhQl1USRyvjm/omeyQgFR2i/Hb7jvKEvN6l1AnhyIa2Vbsmov26UlaTEeSNr4aNg4sMy4L3X5Q3HO1Yg+EROzFGgHAUB3sU9ENKmObbkSEgFW1mVIuKN1V3Za0M0wXZPnTBnPyQIjy8hVtUVDKO5+Q4xbBIMqAxEA+AqHaukK7fm4WO97QkU2a9tFhGW8ig9Z+CVLRT3rA8lvOswe7YDX+sFvwnB4zrppEThAnrMlU4bd5CmyV/AX6HF1saZRio1g="

after_deploy:
- echo "done deploying"
