language: java
jdk:
  - openjdk8
sudo : true
addon:
  sonarcloud:
    token:
      secure: $SECRETACCESSSONAR
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn package
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_deploy:
- echo "done deploying"
