language: java
jdk:
  - openjdk8
addon:
  sonarcloud:
    token:
      secure: $SECRETACCESSSONAR

script:
  - mvn package
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_deploy:
- echo "done deploying"
