language: java
jdk:
  - openjdk11
sudo : true
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "dylanlicho"
    token: $SECRETACCESSSONAR
script:
  - mvn package
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_deploy:
- echo "done deploying"
